dist: bionic
language: go
go:
  - "1.12.x"

services:
  - docker

env:
  global:
    # This is FUZZIT_API_KEY. see https://docs.travis-ci.com/user/environment-variables/#encrypting-environment-variables for how to create secrets in Travis.
    secure: "mUwEzKZKeF6nLswJOCsYxBIQct7v79Wz0ZfiRvPtpKdPD0hNsWHZHXd25E1gTDyAxwUZ1jXoOhMBBUejEAMEe8P64Ali4GZqADxK5JrBGfLNmfvwQJNiJQEyazwhD5m5X+N4ypaxgAfU2jjKn+14u9eKqOYjnKjMbZB2eyEH+F+xtpqA9UsdLbVaI/Pok2CooOk/9sWMxtbqIbwIlqb4l3Sld4/SH3ag7jDWdmcM7sVDALAlDNESGgigjJ47J8uVkV/+kL1CPJY9VfpcXPTgrZmep7QR7/qb2gKGqJgz7dYNLa/iv8vENMyycLsh5GtJzeZU3dLHdDIZH8iUf9+OEr3XKZq0JAh2najxPDrc4A/3VjTPNSgZGEuqTbt1EKGRsVNSIUoBemDobcIEKsyUInQobF2ievtaJqACFG6iVTX2bykS2Y75P0XzHKAiso+Yer0JeAD+xhkzC+m78Gr//Bpb2t2ty2bwgKyukUIbm/Xzmg7yGsl0HFQ6B3AsL0LklHgwHLIPrOcvBZG7F9w4l8U11s3D9e4Ic1P3V5TGABzZ3QvKHmj6iMvAFuuF749tR9iH14ryHyPg50QshoOPYLWLhsCQWOkJ4haa49NsfJMB9ZwJWceq0gc6wA51J7tnqEivohWiwZrZo6uDlHdn/oO1IbwqlWc16FnbSjB5DxY="

jobs:
  include:
    - stage: Build, Unit-Tests & Fuzz-Tests
      go: 1.12.x
      script:
        - go build ./...
        - go test ./...
        - ./ci/fuzzit.sh sanity

    - stage: Fuzzit (Fuzzing)
      if: branch = master AND type IN (push)
      go: 1.12.x
      script:
        - ./ci/fuzzit.sh fuzzing

